#!/bin/bash

set -e

source "sh/configuration"
source "sh/formatting"
source "sh/homebrew"
source "sh/zsh"
source "sh/rvm"
source "sh/rubygems"
source "sh/bundler"
source "sh/cask"
source "sh/osx"

hello() {
  title "Welcome"

  info "This setup will provision your OS X %s workstation. It consists out of the following steps:\n\n" $(sw_vers -productVersion)
  info "  1. Install, update and configure Homebrew."
  info "  2. Install or upgrade the Homebrew formulas."
  info "  3. Configure zsh as the default shell."
  info "  4. Install RVM."
  info "  5. Install the configured Rubies and set %s as the default version." $DEFAULT_RUBY_VERSION
  info "  6. Install Bundler and upgrade to the latest Rubygems version."
  info "  7. Install Homebrew Cask."
  info "  8. Install or upgrade the list of OS X applications using Homebrew Cask."
  info "  9. Configure OS X specific settings."
  info " 10. Run any setup from %s." $LOCAL_WORKSTATION_CONFIGURATION
  info "For more information see the README."

  confirm
}

confirm() {
  read -p "   Do you want to continue? (y/N) " response
  if [[ ! $response =~ ^([yY][eE][sS]|[yY])$ ]]; then
    fail "Quitter!"
    exit
  fi
}

goodbye() {
  info "Your OS X %s workstation has been provisioned." $(sw_vers -productVersion)
  success "Systems ready."
}

setup() {
  hello

  setup_homebrew

  brew_install_or_upgrade "zsh"
  brew_install_or_upgrade "git"
  brew_install_or_upgrade "ack"
  brew_install_or_upgrade "macvim"
  # brew_install_or_upgrade "postgres"
  # brew_install_or_upgrade "sqlite"
  # brew_install_or_upgrade "redis"
  brew_install_or_upgrade "openssl"
  # brew_install_or_upgrade "imagemagick"
  # brew_install_or_upgrade "qt"

  brew_force_link "openssl"
  # brew_force_launchctl_restart "postgres"
  # brew_force_launchctl_restart "redis"

  setup_zsh

  setup_rvm
  setup_rubygems
  setup_bundler

  brew tap "caskroom/cask"
  brew_install_or_upgrade "brew-cask"
  cask_install_or_upgrade "1password"
  cask_install_or_upgrade "appcleaner"
  cask_install_or_upgrade "coconutbattery"
  cask_install_or_upgrade "daisydisk"
  cask_install_or_upgrade "dropbox"
  cask_install_or_upgrade "flux"
  cask_install_or_upgrade "rowanj-gitx"
  cask_install_or_upgrade "google-chrome"
  cask_install_or_upgrade "colorpicker-hex"
  cask_install_or_upgrade "iterm2"
  cask_install_or_upgrade "karabiner"
  cask_install_or_upgrade "slack"
  cask_install_or_upgrade "spectacle"
  cask_install_or_upgrade "spotify"
  cask_install_or_upgrade "virtualbox"
  cask_install_or_upgrade "vagrant"

  setup_osx

  goodbye
}

setup

if [ -f $LOCAL_WORKSTATION_CONFIGURATION ]; then
  . $LOCAL_WORKSTATION_CONFIGURATION
fi
