#!/bin/bash

cask_install_or_upgrade() {
  local cask="$1"

  if cask_is_installed "$cask"; then
    info "Cask %s has already been installed. Skipping..."
  else
    info "Installing %s..." "$cask"
    brew cask install "$cask"
  fi
}

cask_is_installed() {
  local name=$(cask_alias "$1")

  brew cask list -1 | grep --fixed-strings --quiet --line-regexp "$name"
}

cask_alias() {
  brew cask info "$1" 2>/dev/null | head -1 | awk '{gsub(/:/, ""); print $1}'
}
