#!/bin/bash

setup_homebrew() {
  title "Homebrew"

  install_homebrew
  update_homebrew
}

install_homebrew() {
  if ! command -v brew &>/dev/null; then
    info "Installing Homebrew..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    configure_path
    success "Homebrew has been installed."
  else
    info "Homebrew has already been installed. Skipping..."
  fi
}

configure_path() {
  found_path=$(echo $PATH | grep -o -E -m1 $HOMEBREW_PATH | head -1)

  if [[ ! $found_path == $HOMEBREW_PATH ]]; then
    echo "# added by workstation setup" >> "$HOME/.zshrc"
    echo 'export PATH="$HOMEBREW_PATH:$PATH"' >> "$HOME/.zshrc"
  fi
}

update_homebrew() {
  info "Updating Homebrew formulas..."
  brew update
}

brew_install_or_upgrade() {
  if brew_is_installed "$1"; then
    if brew_is_upgradable "$1"; then
      info "Upgrading %s..." "$1"
      brew upgrade "$@"
    else
      info "Already using the latest version of %s. Skipping..." "$1"
    fi
  else
    info "Installing %s..." "$1"
    brew install "$@"
  fi
}

brew_is_installed() {
  local name="$(brew_formula_alias "$1")"

  brew list -1 | grep -Fqx "$name"
}

brew_is_upgradable() {
  local name="$(brew_formula_alias "$1")"

  ! brew outdated --quiet "$name" >/dev/null
}

brew_force_link() {
  brew unlink "$1" && brew link "$@" --force
}

brew_force_launchctl_restart() {
  local name="$(brew_formula_alias "$1")"
  local domain="homebrew.mxcl.$name"
  local plist="$domain.plist"

  fancy_echo "Restarting %s..." "$1"
  mkdir -p "$HOME/Library/LaunchAgents"
  ln -sfv "/usr/local/opt/$name/$plist" "$HOME/Library/LaunchAgents"

  if launchctl list | grep -Fq "$domain"; then
    launchctl unload "$HOME/Library/LaunchAgents/$plist" >/dev/null
  fi

  launchctl load "$HOME/Library/LaunchAgents/$plist" >/dev/null
}

brew_formula_alias() {
  brew info "$1" 2>/dev/null | head -1 | awk '{gsub(/:/, ""); print $1}'
}
