#!/bin/bash

setup_osx() {
  title "OS X Settings"

  info "Setting the default screencapture location to %s..." $DEFAULT_SCREENCAPTURE_LOCATION
  defaults write com.apple.screencapture location $DEFAULT_SCREENCAPTURE_LOCATION
  success "OS X specific settings have been set."
}
