#!/bin/bash

setup_rvm() {
  title "RVM"

  install_rvm
  install_rvm_requirements

  rvm_configure_as_function
  rvm_install_rubies ${RUBY_VERSIONS[*]}
  rvm_configure_default_ruby $DEFAULT_RUBY_VERSION
}

install_rvm() {
  if ! command -v rvm &>/dev/null; then
    info "Installing RVM..."
    \curl --silent --show-error --location https://get.rvm.io | bash -s stable
    success "RVM has been installed."
  else
    info "RVM has already been installed. Skipping..."
  fi
}

install_rvm_requirements() {
  info "Installing RVM requirements..."
  rvm requirements
  success "RVM requirements have been installed."
}

rvm_install_rubies() {
  ruby_versions=$@

  for ruby_version in $ruby_versions; do
    rvm_install $ruby_version
  done
}

rvm_install() {
  local ruby_version="$1"

  if rvm list | grep --fixed-strings --quiet "$ruby_version"; then
    info "Ruby version %s has already been installed." "$ruby_version"
  else
    info "Installing Ruby version %s." "$ruby_version"
    rvm install "$ruby_version"
    success "Ruby version %s has been installed." "$ruby_version"
  fi
}

rvm_configure_as_function() {
  info "Configuring RVM as a function..."
  [[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
  success "RVM has been configured as a function."
}

rvm_configure_default_ruby() {
  local ruby_version="$1"

  info "Configuring Ruby version %s as the default..." "$ruby_version"
  rvm use "$ruby_version" --default
  success "Ruby version %s is configured as the default." "$ruby_version"
}
